Homework fifth
DomPrce/SofaScore2024 pull request #10
Opened 2024-05-24 08:33 UTC by DomPrce

2024-05-24 08:33 UTC, DomPrce commented
Konflikte rjesimo nakon, mislim da su sitnice samo

2024-05-27 13:52 UTC, bolekralj requested changes
Sad kad si dodao prave podatke mozes sve ove vezano za mockanje pobrisat poput Event-a i MockData.
Takoder Trenutno pozivas fetchEvents u MainViewController-u I u LeagueViewController-u pa mislim da je to redundatno. Odluci se na kojem ces mjestu to pozivat i onda najbolje proslijedi podatke jedno drugome jer nema smisla dva puta

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Client/ApiClient.swift
> +        }
jel bi mogao ovu metodu izdvojit u zasebnu u funckiju koja se zove tipa loadData(from: url) pa da nam se ovo ne ponavlja

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/LeagueMatchesViewController.swift
> +    private var exampleLeague: Tournament?
```suggestion
    private var exampleTournament: Tournament?
```

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/EventsForSportAndDate.swift
> +struct EventsForSportAndDate: Codable {
Jel moze samo Event? brijem da je ovo nepotrebno

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/EventSport.swift
> +struct EventSport {
Mozda TabSportModel

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/LeagueMatchesViewController.swift
> +    private var exampleLeague: Tournament?
zapravo ovo uopce ne koristis vise pa ti ni ne treba

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/LeagueMatchesViewController.swift
> +    private var groupedEvents: [Tournament: [EventsForSportAndDate]] = [:]
takoder ja bi tu imao samo groupedEvents i u njegov didSet stavis ovo. Dok ti ovi Eventi nisu ni potrebni

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/LeagueMatchesViewController.swift
> +                self.tableView.reloadData()
ne treba ti self

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/LeagueMatchesViewController.swift
> +                self.tableView.reloadData()
i ovo tu napises samo i onda mozes pobrisat events gore
```suggestion
                groupedEvents = Dictionary(grouping: fetchedEvents, by: { $0.tournament })
                tableView.reloadData()
```

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/MainViewController.swift
> -extension MainViewController: BaseViewProtocol {
ovo nisi trebao pobrisati, pa vrati

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/MainViewController.swift
> +        switchToSportViewController(sportSlug: currentSportSlug, date: date)
ako se promijeni datum onda ne trebamo i sport mijenjat? tu ti treba neka logika za samo update trenutnog controllera

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/MainViewController.swift
> +        switchToSportViewController(sportSlug: sportSlug, date: currentDate)
i tu isto

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/CalendarView.swift
> +            moveUnderline()
indentacija kriva

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/DateCellView.swift
> +    private let underlineView = UIView()
jel ovo uopce koristis ako imamo i tamo isto underlineView?

2024-05-27 13:52 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/DateCellView.swift
> +        setupConstraints()
stavi u ekstenziju

2024-05-28 20:21 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/LeagueMatchesViewController.swift
> +    private var exampleLeague: Tournament?
+

2024-05-28 20:22 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Client/ApiClient.swift
> +        }
+

2024-05-28 20:23 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Models/EventsForSportAndDate.swift
> +struct EventsForSportAndDate: Codable {
+

2024-05-28 20:24 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Models/EventSport.swift
> +struct EventSport {
+

2024-05-28 20:28 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/LeagueMatchesViewController.swift
> +    private var groupedEvents: [Tournament: [EventsForSportAndDate]] = [:]
+

2024-05-28 20:29 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/LeagueMatchesViewController.swift
> +                self.tableView.reloadData()
+

2024-05-28 20:32 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/MainViewController.swift
> -extension MainViewController: BaseViewProtocol {
+

2024-05-28 20:34 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/MainViewController.swift
> +        switchToSportViewController(sportSlug: currentSportSlug, date: date)
+

2024-05-28 20:37 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Controllers/MainViewController.swift
> +        switchToSportViewController(sportSlug: sportSlug, date: currentDate)
+

2024-05-28 20:39 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Views/CalendarView.swift
> +            moveUnderline()
+

2024-05-28 20:41 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Views/DateCellView.swift
> +    private let underlineView = UIView()
+

2024-05-28 20:42 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Views/DateCellView.swift
> +        setupConstraints()
+

2024-06-10 22:21 UTC, merged