Homework first
DomPrce/SofaScore2024 pull request #2
Opened 2024-03-18 00:10 UTC by DomPrce

showcasing dynamic match and league views, utilizing AutoLayout and custom UIViews for displaying sports event data, with adaptive design for varied content lengths.

2024-03-18 11:31 UTC, bolekralj commented
Molim te azuriraj .gitignore tako da ne vidimo ni .dsStore a nisam siguran za ovaj neki IDECheck to trebamo provjeriti

2024-03-18 12:28 UTC, bolekralj requested changes
Generalno je okej. Dodaj snapkit i prebaci styling u styleViews ako ti ista nije jasno javi se slobodno :)

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/Event.swift
> +}
Mozes li svuda primijeniti stil da imamo razmak nakon imena i prazan prvi red
```suggestion
struct League {

    var country: String
    var leagueName: String
}
```

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/Event.swift
> +extension Event {
iz kojeg razloga si tu koristio ekstenziju, ne vidim neku dobit, mozes imat jednostavno struct sa var formattedStartTime. Ima mi smisla odvajati u ekstenzije ako imamo neki protocol ili imamo neku vecu cijelinu

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/Event.swift
> +extension MatchStatus {
takoder i ovo bi dodao kao computed property bez ekstenzije

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/Event.swift
> +enum MatchStatus{
razmak i novi red

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/Event.swift
> +struct Event{
razmak i novi red

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +class ViewController: UIViewController {
bilo bi ljepse da je ovo neko deskriptivnije ime od ViewController, tipa `LeagueMatchesViewController`

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +
pobrisi

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +    override func viewDidLoad() {
mozes koristiti i za UIViewController BaseView protokol da bude konzistentno

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +        let startTime1 = Date(timeIntervalSince1970: 1710676800)
mozes li ove konstante prebaciti u Model ili nesto za konstatne

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +class LeagueView: BaseView {
istrazi si malo sto je final class

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +    private let eventCellsEventCellView: UIView = {
ovo ime mi nije uopce jasno

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Abstractions/Colors.swift
> +extension UIColor {
Zasto @nonobjc i daj razmake izmedu elemenata

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Abstractions/Colors.swift
> +extension UIColor {
i zasto class?

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Abstractions/Fonts.swift
> +extension UIFont {
takoder ti ne treba tu nigdje class i tu je super indetation :) tako svuda

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/AppDelegate.swift
> +
obrisi red

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/AppDelegate.swift
> +    var window:UIWindow?
razmak

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Base.lproj/LaunchScreen.storyboard
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
mislim da nam nije potreban file pa ga pobrisi

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/Event.swift
> +        case .isFinished: return "Finished"
mislim da cak swift podrazva i pisanje bez returna. Takoder meni draze kad je case svaki u svom redu al ti vidi :)

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +
dovoljan je jedan prazan

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
tu mozes isto koristit SofaAcademic i rasporedit po metodama

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +    private let country: UILabel = {
ove sve uikit komponente si napisao super i lijepo, ali je bila ideja da njih napises npr ovako
`private let countryLabel: UILabel  = .init() `
i onda mu styling dodas u dijelu style views koje imas iz modula

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +    private let rightPointer: UIImageView = {
u swiftu kad dajemo imena view komponentama pravilo je da ih nazoves ime + ime komponente. Npr. countryLabel,
leagueImageView itd.

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +        label.textColor = UIColor.onSurfaceOnSurfaceLv2
mislim da ti tu ne treba UIFont ni UIColor da mozes samo s tockom ali bi volio da sve prebacis onako kako sam gore napisao.

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +        super.addViews()
ne trebas zvati super jer on nista ne radi

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +        super.setupConstraints()
maknuti super i sve napraviti sa snapkitom

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +
prazne redove

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +    private let eventCellsEventCellView: UIView = {
ovo ko i u LeagueView-u prebaciti na onaj nacin

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +    private let eventCellsEventCellView: UIView = {
jel ovo neki background view?

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +    private let teamOneLabel: UILabel = {
mozda dodati i name u ime

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +    override func setupConstraints() {
prebaciti sve na snapkit

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +        teamTwoScoreLabel.text = "\(teamTwoScore)"
mozes koristit tipa teamOneScore.description to je funkcija za string od int-a

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +
jedan red je dosta

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +        switch event.matchStatus {
ovo bi izdvojio u zasebnu metodu tipa update status

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +            case .inProgress:
mislim da su tu prazni redovi overkill i negdje ti je indetation sjeban pa to popravi. takoder nemoras pisat UIFont i UIColor tu nigdje.

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +
makni ove prazne redove

2024-03-18 12:28 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +            teamOneLabel.textColor = UIColor.onSurfaceOnSurfaceLv1
tu bi mogao dodat ovako neku strukturu

```
struct ValuePair<Value> {

        let left: Value
        let right: Value
    }
```

i preko nje definirati te boje

npr.
```
static func getTeamNameColors(for status: EventStatus?, winnerCode: WinnerCode?) -> ValuePair<UIColor> {
        var leftColor: UIColor = .nLv1
        var rightColor: UIColor = .nLv1

        if status == .finished,
           let winnerCode {
            if winnerCode == .home {
                rightColor = .nLv3
            } else if winnerCode == .away {
                leftColor = .nLv3
            }
        }
        return ValuePair(left: leftColor, right: rightColor)
    }
```

2024-03-18 12:55 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/Event.swift
> +    var matchStatus: MatchStatus
mislim da ti sve ovo moze bit let

2024-03-22 13:00 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Abstractions/Colors.swift
> +extension UIColor {
ovo sam kopirao izravno sa zeppelina, a bez class ne radi

2024-03-22 13:00 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Abstractions/Fonts.swift
> +extension UIFont {
isto kopirao sa zeppelina

2024-03-22 13:14 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Abstractions/Colors.swift
> +extension UIColor {
oki ostavi tako onda i fonts isto, my bad

2024-03-25 09:35 UTC, bolekralj requested changes
Prebacio si se na snapkit, ali mislim da ga nisi koristio na najbolji nacin tako da probaj to malo istraziti i povezati elemente preko susjeda. Mogu ti to pokazati ako treba :)

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Abstractions/Constants.swift
> +
Ako radis konstante onda napravi tipa caseless Enum imena Constants i u njega stavis static let startTIme1 al ovo nije potrebno za ovaj slucaj mislio sam vise zasto radis preko ovog timeIntervala a ne izravno Date?

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/Event.swift
> +struct League{
```suggestion
struct League {
```

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/Event.swift
> +    var leagueName: String
```suggestion
    let country: String
    let leagueName: String
```

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/Event.swift
> +    var matchStatus: MatchStatus
jel moze?

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/Event.swift
> +enum MatchStatus{
```suggestion
enum MatchStatus {
```

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/Event.swift
> +    var description: String {
Praksa je kod nas da stavljamo prazan red uvijek nakon Definiranja klase, strukture, neke ekstenzije i slicno. Dok ovdje ti ne treba kod svake varijable novi red

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Models/Event.swift
> +
ne trebaju prazni redovi i odluci se oces li u istom redu ili svaki u novi kod returna

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +class LeagueMatchesViewController: UIViewController, BaseViewProtocol {
Trebao bi ovo odvojit, dodat `extension LeagueMatchesViewController: BaseViewProtocol`

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +
ne treba prazan red

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +
ova funkcija ti ne treba onda to isto trebas stavit u addViews i style views

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +
znaci u ovim funkcijama nam ne treba prazan red na pocetku i kraju to samo u vecim cjelinama

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +
```suggestion
```

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +
izbrisi

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +
izbrisi praza
```suggestion
```

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +
```suggestion
```

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.top.equalToSuperview().offset(100)
ovaj tu offset mi nije uopce jasan. Al ajmo od pocetka zapravo koja je ideja snapkita i kako ga koristiti tj autolayout-a. Smisao je da bi view sam se trebao prilagodavati velicinama elemenata preko constainta-ova. Pa zapravo ne bi ovom container-u uopce trebao postavaljat visinu nego bi on to izracuo sam preko elemenata. Ako ti nije ovo skroz jasno mozemo sutra proc kroz to uzivo.

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +
ovi prazni redovi samo kako smo rekli u onom komentaru u drugom file-u

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.leading.equalTo(leagueCellView.snp.leading).offset(16)
znaci ovdje mozes slobodno stavit equal to superview jer mu to i je superview
```suggestion
            $0.leading.equalToSuperview().inset(16)
```

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.top.equalTo(leagueCellView.snp.top).offset(12)
ovdje isto

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.width.height.equalTo(32.0)
mozes skratit 
```suggestion
            $0.size.equalTo(32.0)
```

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.top.equalTo(leagueCellView.snp.top).offset(20)
ovo bi radije postavio constraint na element koji se nadovezuje tipa
```suggestion
            $0.leading.equalTo(leagueImageView.snp.trailing).offset(16)
            $0.top.equalToSuperview().inset(20)
```

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.height.equalTo(16.0)
labelu ne bi trebao nikad height postavljat ako ne moramo, jer bi on trebao bit visok koliko su mu i slova

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +        }
ovdje vrijede komentari ko tamo gore

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +        }
ovdje isto povezi preko drugih elemenata i ako zelimo da nam view nema svoju visinu tu moramo dodati i bottom constraint

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +    }
ovo je super bravo!

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +        case home
```suggestion

        case home
```

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +        }
isto ko i za cellView u league-u treba ga drugacije postaviti

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +            $0.leading.equalTo(matchCellView.snp.leading).offset(104)
isto mozes equal to superview

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +        }
ovo je dobro napisano samo nam ne treba height, tak sad i sve druge povezi

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +            $0.leading.equalTo(matchCellView.snp.leading).offset(320)
tipa ovo ne bi sigurno dobro izgledalo na svim ekranima, pa iz tog razloga bi trebao povezat preko susjeda

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +            $0.height.equalTo(16.0)
super, bez heighta

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +    private let matchCellverticalDivider = UIView()
```suggestion
    private let matchCellVerticalDivider = UIView()
```

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +    private let matchCellView = UIView()
ovo si dodavao container i tu i u liga view-u. To mi je okej u slucajevima kada taj container view ima neku drugu boju, ili je rounded ili ima tap na sebi. Dok u ovom slucaju nista nam on ne radi pa bi rekao da je redundatnat

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +    static func getTeamNameColors(for status: MatchStatus, winnerCode: WinnerCode?) -> ValuePair<UIColor> {
ovo ti ne treba bit static

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +        let colors = MatchView.getTeamNameColors(for: status, winnerCode: winnerCode)
i kad nece bit static moc ces ovako samo
```suggestion
        let colors = getTeamNameColors(for: status, winnerCode: winnerCode)
```

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +        }()
ovo bi izdvojio u zassebnu neku metodu getWinnerCode

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +
jedan red prazan dovoljan

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +        }()
mogo bi i taj podatak slat kroz model mozda tako najbolje

2024-03-25 09:35 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +        let scoreColor: UIColor = status == .inProgress ? .specificLive : colors.left
tu bi isto trebao pokazat drugu boju za ekipu koja je pobijedila zar ne?

2024-03-26 07:59 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
Promjeni ime isto

2024-03-26 08:02 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +        }
i radije ogranici label sa obje strane nego da mu bas das width jer ko zna tu moze bit tekst razlicit duzina

2024-03-26 08:03 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.top.equalToSuperview().offset(100)
na ovaj princip mislim
```
 leagueCountryLabel.snp.makeConstraints {
            $0.leading.top.equalToSuperview().inset(12)
            $0.size.equalTo(32)
        }

 leagueNameLabel.snp.makeConstraints {
            $0.leading.equalTo(leagueCountryLabel.snp.trailing).offset(8)
            $0.top.equalToSuperview().inset(20)
        }
```

2024-03-29 09:16 UTC, bolekralj requested changes
Bolje je dosta, ali i dalje postavljas ti visinu matchView-u sto ne zelimo. molim te taj dio jos popeglaj i prodi sve komentare jos jednom

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +        let leagueView = LeagueView()
ovo bi stavio di je i stackView gore

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +        leagueView.configure(with: exampleLeague)
onda ove dvije metode u style

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +            $0.centerX.centerY.equalToSuperview()
mozes i samo al tipa da tu imamo sad 20 evenat-a kako bi ovo izlgedalo?
```suggestion
            $0.center.equalToSuperview()
```

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +        }
kad izdvojis leagueView gore nece ti trebati if let ovaj

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +        }
mislim da sam ti ovo pisao vec da ne zelimo mi tocno rec matchVIew-u koliko je visok nego da si on to sam odredi preko svojih UI elemenata

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.top.equalToSuperview().offset(100)
MIslim da ti ovo nije dobro postavljeno, cemu sluzi taj offset?

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.height.equalTo(56.0)
i on ne bi trebao imati svoj eksplicitni height

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.width.equalTo(50)
sta ako je ime zemlje malo vece oce li to stat?

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.width.equalTo(91.0)
sta ako je ime lige dulje?

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +        leagueRightPointerImageView.snp.makeConstraints {
mislim da slici trebas dat sirinu i visinu?

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +    private let matchCellView = UIView()
i dalje mislim da ti cellView ne treba ni tu ni u lizi

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +            $0.height.equalTo(56.0)
sve isto ko i za ligu

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +            $0.leading.equalToSuperview().inset(104)
ovo mi se cini krivo isto

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +            $0.leading.equalToSuperview().inset(104)
on bi se trebao nadovezat na teamOneImageView

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +            $0.width.equalTo(192)
radije ga ogranici sa obje strane nego postaviti bas sirinu. Postavljanje sirine ima smisla ako znamo da ce uvijek biti isti tekst dok ovo u praksi uvijek moze biti drugaciji team

2024-03-29 09:16 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +            $0.width.equalTo(192)
isto ko gore

2024-04-03 08:43 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.size.equalTo(32.0)
moze i 32 samo

2024-04-03 08:44 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.trailing.lessThanOrEqualToSuperview().inset(-129)
sta ti je ovo?

2024-04-03 12:58 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +            $0.bottom.equalToSuperview().inset(8)
Moses samo staviti bottom.equalToSuperview().inset(10) prije merg-a

2024-04-04 10:32 UTC, bolekralj approved these changes
samo dodaj onaj bottom i mozes mergat

2024-04-04 10:32 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.trailing.lessThanOrEqualToSuperview().inset(-129)
ne kuzim ovo

2024-04-04 10:32 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
>                  }
ovo ti ne bi uopce trebalo jer bi ti elementi to sami trebali znat

2024-04-04 10:32 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/LeagueView.swift
> +            $0.top.equalToSuperview().inset(12)
mislim da ti tu i dalje fali bottom

2024-04-04 11:33 UTC, merged