Homework second
DomPrce/SofaScore2024 pull request #3
Opened 2024-03-25 22:51 UTC by DomPrce

2024-03-26 07:54 UTC, bolekralj requested changes
Napravi jos Ligu kao header view of section i pogledaj komentare

2024-03-26 07:54 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +class LeagueMatchesViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
jel mozes svaku odvojit u zasebnu npr tu ostavis i onda dodas ispod ekstenzije za ove ostale dvije
```suggestion
class LeagueMatchesViewController: UIViewController {
```

2024-03-26 07:54 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +        tableView.separatorStyle = .none
ovo mozes u styleViews

2024-03-26 07:54 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
>      private func setupView() {
radije napravi da opet pratimo addViews, style i setup

2024-03-26 07:54 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy.xcodeproj/project.pbxproj
> -		8D8E85652BA684AB00D3475D /* LeagueView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = LeagueView.swift; sourceTree = "<group>"; };
ne trebas brisati LeagueView mislim da si trebao i za njega napraviti cell tako da ti taj dio fali

2024-03-26 07:54 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +        return cell
ovo je super, bravo!

2024-03-26 07:54 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
ajde isprobaj jel mozemo imat da si on sam zna visinu i da nam ova metoda uopce ne treba pa mi javi jel to radi

2024-03-26 07:54 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
>          }
ja bi radije da ti das tableView da bude preko cijelog ekrana to mi nekak ima vise smisla ili da bude ono neki padding od rubova bit ce ljepse

2024-03-26 07:54 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchViewCell.swift
> +class MatchViewCell: UITableViewCell {
ne moras micat final, al ja bi da i dalje MatchViewCell extenda BaseViewProtocol taj dio nisi trebao mijenjat

2024-04-04 10:43 UTC, bolekralj requested changes

2024-04-04 10:43 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
promijeni i ime file-a

2024-04-04 10:43 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> -class LeagueMatchesViewController: UIViewController, BaseViewProtocol {
vrati tu BaseViewProtocol i rasporedi stvari po tim metodaama

2024-04-04 10:43 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
>      private func setupView() {
nisi ovo

2024-04-04 10:43 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +            $0.leading.trailing.equalToSuperview()
ovo mozes i skratit sa samo .edges

2024-04-04 10:43 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +extension LeagueMatchesViewController: UITableViewDelegate{
```suggestion
extension LeagueMatchesViewController: UITableViewDelegate {
```

2024-04-04 10:43 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +    }
bravo!

2024-04-04 10:43 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +extension LeagueMatchesViewController: UITableViewDataSource{
```suggestion
extension LeagueMatchesViewController: UITableViewDataSource {
```

2024-04-04 10:43 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
ime file bi ti trebalo pratit ime glavne klase, te tu isto moras dodat BaseViewProtocol

2024-04-04 11:44 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +extension LeagueMatchesViewController: UITableViewDataSource{
+

2024-04-04 11:45 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +    }
+

2024-04-04 11:45 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +            $0.leading.trailing.equalToSuperview()
+

2024-04-04 11:45 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> +extension LeagueMatchesViewController: UITableViewDelegate{
+

2024-04-04 11:49 UTC, DomPrce commented on SofaScoreAcademy/SofaScoreAcademy/ViewController.swift
> -class LeagueMatchesViewController: UIViewController, BaseViewProtocol {
+

2024-04-04 13:29 UTC, bolekralj requested changes
Moras jos dodat u MatchViewCell ekstenziju za BaseViewProtocol. Ostalo je dobro tako da bi ovo mogli isto danas spojit :)

2024-04-04 13:29 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/LeagueMatchesViewController.swift
> +
samo jedan prazan :)

2024-04-04 13:29 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/LeagueMatchesViewController.swift
> +class LeagueMatchesViewController: UIViewController {
super si ovo

2024-04-04 13:29 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
> +class MatchView: UITableViewCell {
```suggestion
class MatchViewCell: UITableViewCell {
```

2024-04-04 13:29 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchView.swift
E sad kak si dodao u LeagueMatchesViewController ekstenziju BaseViewProtocol tako trebas i tu.

2024-04-04 13:30 UTC, bolekralj commented
Jel znas rijesiti konflikte?

2024-04-05 07:21 UTC, bolekralj approved these changes
najs

2024-04-05 07:21 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchViewCell.swift
> +    func getTeamNameColors(for status: MatchStatus, winnerCode: WinnerCode?) -> ValuePair<UIColor> {
mislim da i ovu i getTeamScoreColors mozes isto private stavit cak ih i mozes stavit u private extension ako ti se to svida

2024-04-05 07:21 UTC, bolekralj commented on SofaScoreAcademy/SofaScoreAcademy/Views/MatchViewCell.swift
> +extension MatchViewCell: BaseViewProtocol{
```suggestion
extension MatchViewCell: BaseViewProtocol {
```

2024-04-05 14:22 UTC, merged